/**
 * `vsa setup` (FR-50, ARCHITECTURE.md §3 step 1 / §11) — deploy a new
 * per-vault worker + R2 bucket into the user's own Cloudflare account:
 *
 *   1. Ask the vault name → derive worker + bucket names (slug + suffix).
 *   2. Authenticate: drive `npx wrangler` (whoami → login → whoami), or the
 *      non-interactive `--api-token` + `--account-id` path (REST probe +
 *      wrangler env vars).
 *   3. Download the pinned VaultSyncforAgents worker release bundle
 *      (`worker-bundle.zip`, sha-verified + size-capped) and extract it
 *      into a fresh deploy directory.
 *   4. Generate the deploy directory's wrangler.jsonc (same shape as the
 *      template repo's).
 *   5. Create the R2 bucket if missing, then `wrangler deploy`.
 *   6. Print the worker URL + claim walkthrough, offer to open the browser.
 *
 * Every Cloudflare touch goes through the `CloudflareControl` seam — tests
 * fake it; production shells out (`src/cloudflare.ts`).
 */

import { mkdir, writeFile } from 'node:fs/promises';
import { join, resolve } from 'node:path';
import { CommandError, type VsRuntime } from '../runtime.js';
import {
  createCloudflareControl,
  type CloudflareAccount,
  type CloudflareControl,
} from '../cloudflare.js';
import {
  PINNED_BUNDLE_SHA256,
  PINNED_RELEASE,
  RELEASE_BUNDLE_URL,
  WORKER_COMPATIBILITY_DATE,
  randomSuffix,
  deriveWorkerName,
} from '@vsa/core';

// The pin, the bundle URL, and the worker/bucket naming live in `@vsa/core`
// (core/src/deploy.ts) — the single source of truth shared with the plugin's
// in-app setup wizard, so the two provisioners cannot drift onto different
// releases or name shapes. Re-exported here for the CLI's own tests and
// callers; `renderWranglerConfig` below consumes the two values it needs.
export {
  PINNED_RELEASE,
  PINNED_BUNDLE_SHA256,
  RELEASE_BUNDLE_URL,
  WORKER_COMPATIBILITY_DATE,
  slugify,
  randomSuffix,
  deriveWorkerName,
  deriveBucketName,
} from '@vsa/core';

// --- config generation ----------------------------------------------------------------------

export interface WranglerConfigInput {
  workerName: string;
  bucketName: string;
  /** Directory the release bundle's `dashboard/` assets land in, relative to the config. */
  assetsDirectory?: string;
}

/**
 * Render the deploy directory's wrangler.jsonc. Kept in lockstep with
 * template/wrangler.jsonc (bindings: ROOM/VaultRoom SQLite DO, BUCKET R2,
 * weekly GC cron, dashboard assets when present).
 */
export function renderWranglerConfig(input: WranglerConfigInput): string {
  // Mirrors packages/worker/wrangler.jsonc (incl. the dashboard assets
  // binding: worker-first routing + SPA fallback).
  const assets =
    `  // Dashboard SPA shipped inside the release bundle (dist/dashboard), served\n` +
    `  // by the worker at / — no second deployment (ARCHITECTURE.md §10).\n` +
    `  "assets": {\n` +
    `    "directory": "${input.assetsDirectory ?? './dist/dashboard'}",\n` +
    `    "binding": "ASSETS",\n` +
    `    "not_found_handling": "single-page-application",\n` +
    `    "run_worker_first": true\n` +
    `  },\n`;
  return `{
  // Generated by \`vsa setup\` — VaultSync for Agents, one worker per vault
  // (ARCHITECTURE.md §1, FR-20). Deployed from the ${PINNED_RELEASE} release bundle.
  "$schema": "node_modules/wrangler/config-schema.json",
  "name": "${input.workerName}",
  "main": "./dist/worker.js",
  "compatibility_date": "${WORKER_COMPATIBILITY_DATE}",
${assets}  "durable_objects": {
    "bindings": [
      {
        "name": "ROOM",
        "class_name": "VaultRoom"
      }
    ]
  },
  // SQLite-backed Durable Object class registration (wrangler schema has no
  // top-level new_sqlite_classes key — it lives under migrations).
  "migrations": [
    {
      "tag": "0001_initial",
      "new_sqlite_classes": ["VaultRoom"]
    }
  ],
  "r2_buckets": [
    {
      "binding": "BUCKET",
      "bucket_name": "${input.bucketName}"
    }
  ],
  "triggers": {
    // Weekly orphan-blob GC, Mondays 03:00 UTC (ARCHITECTURE.md §7).
    "crons": ["0 3 * * 1"]
  }
}
`;
}

// --- deploy URL parsing ---------------------------------------------------------------------

/** First `https://…workers.dev` URL in wrangler deploy output, if printed. */
export function parseDeployUrl(stdout: string): string | null {
  // Subdomain may be multi-label (worker.<account-subdomain>.workers.dev).
  const match = stdout.match(/https:\/\/[a-z0-9-]+(?:\.[a-z0-9-]+)*\.workers\.dev/i);
  return match === null ? null : match[0];
}

// --- the command ----------------------------------------------------------------------------

export interface SetupParams {
  /** Vault name (prompted when missing). */
  vaultName?: string;
  /** Worker name override (default: derived from the vault name). */
  workerName?: string;
  /** R2 bucket override (default: same as the worker name). */
  bucketName?: string;
  /** Cloudflare API token — selects the non-wrangler-login path. */
  apiToken?: string;
  /** Cloudflare account id (required early when multiple accounts exist). */
  accountId?: string;
  /** Deploy directory (default: ./<workerName>). */
  dir?: string;
  /** Use a local worker-bundle.zip instead of downloading the release. */
  bundlePath?: string;
  /** Skip prompts (fail on anything missing). */
  yes?: boolean;
  /** Open the worker URL in the browser after deploy. */
  open?: boolean;
  /** Deterministic suffix (tests); default is random. */
  suffix?: string;
}

export interface SetupResult {
  vaultName: string;
  workerName: string;
  bucketName: string;
  deployDir: string;
  /** `null` when wrangler did not print one (custom domains / output change). */
  workerUrl: string | null;
  accountId: string | null;
  createdBucket: boolean;
  bundleFrom: string;
}

export async function runSetup(
  runtime: VsRuntime,
  params: SetupParams,
  cloudflare: CloudflareControl = runtime.cloudflare ??
    createCloudflareControl({
      // The release-bundle download must be integrity-verified (pinned
      // digest, else the release's .sha256 sidecar) and size-capped; the
      // legacy warn-and-proceed notice lands in the command's output.
      bundleSha256: PINNED_BUNDLE_SHA256,
      warn: (message) => runtime.output.warn(message),
    }),
): Promise<SetupResult> {
  const out = runtime.output;
  out.log('VaultSync for Agents — worker setup (deploy into YOUR Cloudflare account).');
  out.log('');

  // 1. Names. (A whitespace-only --name is refused, not re-prompted.)
  const provided = params.vaultName?.trim();
  if (params.vaultName !== undefined && provided === '') {
    throw new CommandError('vault name required (pass --name <vault>)');
  }
  const vaultName =
    provided !== undefined && provided !== ''
      ? provided
      : await promptText(runtime, params.yes === true, 'Vault name (shown in the dashboard, e.g. "personal")');
  if (vaultName === '') throw new CommandError('vault name required (pass --name <vault>)');
  const suffix = params.suffix ?? randomSuffix();
  const workerName = params.workerName ?? deriveWorkerName(vaultName, suffix);
  const bucketName = params.bucketName ?? workerName;
  const deployDir = resolve(params.dir ?? workerName);

  // 2. Authenticate → wrangler env vars (empty for the OAuth path — wrangler
  //    uses its stored credentials) + account id.
  const env: Record<string, string> = {};
  let accountId: string | null = params.accountId ?? null;
  if (params.apiToken !== undefined) {
    const account = await authenticateWithToken(runtime, cloudflare, params, env);
    accountId = account.id;
  } else {
    accountId = await authenticateWithWrangler(runtime, cloudflare, params, env, accountId);
  }

  // 3. Bundle: download the pinned release (or copy a local one).
  const zipPath = join(deployDir, 'worker-bundle.zip');
  let bundleFrom: string;
  await mkdir(deployDir, { recursive: true });
  if (params.bundlePath !== undefined) {
    const { copyFile } = await import('node:fs/promises');
    await copyFile(resolve(params.bundlePath), zipPath);
    bundleFrom = resolve(params.bundlePath);
  } else {
    out.log(`Downloading the worker bundle (${PINNED_RELEASE})…`);
    const bytes = await cloudflare.download(RELEASE_BUNDLE_URL);
    await writeFile(zipPath, bytes);
    bundleFrom = RELEASE_BUNDLE_URL;
  }
  out.log('Extracting the bundle…');
  const extract = await cloudflare.extractZip(zipPath, join(deployDir, 'dist'), env);
  if (extract.code !== 0) {
    throw new CommandError(
      `could not extract the worker bundle: ${(extract.stderr || extract.stdout).trim()}`,
    );
  }

  // 4. Generate wrangler.jsonc.
  await writeFile(join(deployDir, 'wrangler.jsonc'), renderWranglerConfig({ workerName, bucketName }));
  out.log(`Prepared the deploy directory: ${deployDir}`);

  // 5. R2 bucket (create if missing).
  const createdBucket = await ensureBucket(runtime, cloudflare, bucketName, env);

  // 6. Deploy.
  out.log(`Deploying worker ${workerName}…`);
  const deploy = await cloudflare.deploy(deployDir, env);
  if (deploy.code !== 0) {
    throw new CommandError(
      `wrangler deploy failed (exit ${deploy.code}): ${(deploy.stderr || deploy.stdout).trim()}`,
    );
  }
  const workerUrl = parseDeployUrl(deploy.stdout);

  // 7. Report + next steps.
  out.log('');
  out.log('Deployed. Next steps:');
  if (workerUrl !== null) {
    out.log(`  1. Open ${workerUrl} in a browser.`);
  } else {
    out.log('  1. Open your worker URL (see the Cloudflare dashboard — wrangler did not print one).');
  }
  out.log('  2. Set the admin passphrase and name the vault — that CLAIMS the worker.');
  out.log('  3. On the dashboard, create a pairing code (Devices → Pair new device).');
  out.log('  4. Pair this machine:  vsa link --url <worker-url> --code <CODE>');
  out.log('');
  out.log(`Deploy directory (re-deploy anytime): ${deployDir}`);

  const wantsOpen =
    params.open === true ||
    (params.open !== false &&
      workerUrl !== null &&
      (await confirm(runtime, params.yes === true, 'Open the worker URL in your browser now?')));
  if (wantsOpen && workerUrl !== null) {
    const opened = await cloudflare.openBrowser(workerUrl);
    if (opened.code !== 0) {
      out.warn(`could not open the browser (${(opened.stderr || '').trim()}) — open ${workerUrl} manually`);
    }
  }

  return {
    vaultName,
    workerName,
    bucketName,
    deployDir,
    workerUrl,
    accountId,
    createdBucket,
    bundleFrom,
  };
}

// --- auth paths -----------------------------------------------------------------------------

/** Wrangler OAuth path: whoami → (login → whoami) → account selection. */
async function authenticateWithWrangler(
  runtime: VsRuntime,
  cloudflare: CloudflareControl,
  params: SetupParams,
  env: Record<string, string>,
  accountId: string | null,
): Promise<string> {
  const out = runtime.output;
  out.log('Checking Cloudflare authentication (npx wrangler whoami)…');
  let info = await cloudflare.whoami();
  if (info.status !== 'ok') {
    if (info.status === 'expired') {
      out.warn('Your wrangler login has expired.');
    } else {
      out.log('You are not logged in to Cloudflare yet.');
    }
    if (runtime.prompts === null) {
      throw new CommandError(
        'not authenticated with Cloudflare — run `npx wrangler login` first, or pass --api-token and --account-id',
      );
    }
    const proceed = await runtime.prompts.confirm('Open your browser to log in to Cloudflare now?');
    if (!proceed) throw new CommandError('cancelled');
    out.log('Starting wrangler login (finish in the browser; this waits for the callback)…');
    const login = await cloudflare.login();
    if (login.code !== 0) {
      throw new CommandError(
        `wrangler login failed (exit ${login.code}): ${(login.stderr || login.stdout).trim()}`,
      );
    }
    info = await cloudflare.whoami();
    if (info.status !== 'ok') {
      throw new CommandError('still not authenticated after wrangler login — try `npx wrangler whoami` manually');
    }
  }
  const account = await pickAccount(runtime, info.accounts, params.accountId);
  out.log(`Authenticated with Cloudflare (account: ${account.name}).`);
  // OAuth path: no env vars — wrangler uses its stored credentials.
  return account.id;
}

/** API-token path: verify via REST, then point wrangler at the token non-interactively. */
async function authenticateWithToken(
  runtime: VsRuntime,
  cloudflare: CloudflareControl,
  params: SetupParams,
  env: Record<string, string>,
): Promise<CloudflareAccount> {
  let token = params.apiToken;
  if (token === undefined || token === '') {
    token = await promptPassword(runtime, params.yes === true, 'Cloudflare API token (Workers Scripts:Edit + R2:Edit)');
  }
  env.CLOUDFLARE_API_TOKEN = token;
  const accounts = await cloudflare
    .restListAccounts(token)
    .catch((error: unknown) => {
      throw new CommandError(error instanceof Error ? error.message : String(error));
    });
  const account = await pickAccount(runtime, accounts, params.accountId);
  env.CLOUDFLARE_ACCOUNT_ID = account.id;
  runtime.output.log(`API token accepted (account: ${account.name}).`);
  return account;
}

/** Pick the account: --account-id, the only one, or an interactive select. */
async function pickAccount(
  runtime: VsRuntime,
  accounts: readonly CloudflareAccount[],
  accountId: string | undefined,
): Promise<CloudflareAccount> {
  if (accountId !== undefined) {
    const match = accounts.find((account) => account.id === accountId);
    if (match !== undefined) return match;
    if (accounts.length === 0) return { id: accountId, name: accountId };
    throw new CommandError(
      `account ${accountId} is not accessible with these credentials — available: ` +
        accounts.map((account) => `${account.name} (${account.id})`).join(', '),
    );
  }
  if (accounts.length <= 1) {
    const only = accounts[0];
    if (only === undefined) {
      throw new CommandError(
        'no Cloudflare accounts visible to these credentials — check the token/account',
      );
    }
    return only;
  }
  if (runtime.prompts === null) {
    throw new CommandError(
      `multiple Cloudflare accounts — pass --account-id <id>. Accounts: ` +
        accounts.map((account) => `${account.name} (${account.id})`).join(', '),
    );
  }
  const selectedId = await runtime.prompts.select(
    'Which Cloudflare account should own this worker?',
    accounts.map((account) => ({
      value: account.id,
      label: `${account.name} (${account.id})`,
    })),
  );
  const selected = accounts.find((account) => account.id === selectedId);
  if (selected === undefined) throw new CommandError(`account ${selectedId} vanished mid-prompt`);
  return selected;
}

// --- bucket ---------------------------------------------------------------------------------

/** `true` when the bucket had to be created. Throws on real failures. */
async function ensureBucket(
  runtime: VsRuntime,
  cloudflare: CloudflareControl,
  bucketName: string,
  env: Record<string, string>,
): Promise<boolean> {
  const out = runtime.output;
  out.log(`Checking the R2 bucket ${bucketName}…`);
  const info = await cloudflare.bucketInfo(bucketName, env);
  if (info.code === 0) {
    out.log('Bucket exists — reusing it.');
    return false;
  }
  out.log('Bucket not found — creating it…');
  const create = await cloudflare.bucketCreate(bucketName, env);
  if (create.code === 0) return true;
  const detail = (create.stderr || create.stdout).trim();
  if (/already exist|10004|bucket name is already taken/i.test(detail)) {
    out.log('Bucket already exists (created concurrently) — reusing it.');
    return false;
  }
  throw new CommandError(
    `could not create the R2 bucket ${bucketName} (exit ${create.code}): ${detail}`,
  );
}

// --- prompt helpers -------------------------------------------------------------------------

async function promptText(runtime: VsRuntime, nonInteractive: boolean, message: string): Promise<string> {
  if (nonInteractive || runtime.prompts === null) {
    throw new CommandError(`${message}: required in non-interactive mode — pass --name <vault>`);
  }
  const answer = await runtime.prompts.text(message);
  return answer.trim();
}

async function promptPassword(runtime: VsRuntime, nonInteractive: boolean, message: string): Promise<string> {
  if (runtime.prompts === null || nonInteractive) {
    throw new CommandError(`${message}: required — pass --api-token`);
  }
  const answer = await runtime.prompts.password(message);
  if (answer === '') throw new CommandError(`${message}: value required`);
  return answer;
}

async function confirm(runtime: VsRuntime, nonInteractive: boolean, message: string): Promise<boolean> {
  if (runtime.prompts === null || nonInteractive) return nonInteractive;
  return runtime.prompts.confirm(message);
}
